### PR TITLE
Git160915/module 08 20230823

### PR DESCRIPTION
**Pull request by git160915**
Completed all assignments from module 8.  Requesting merge into main

### CODE REVIEW

**Review by bdgit00 — COMMENTED** [review]
I'm fine with this change.  Seeking review and approval from @SyntaxXSamurai

**Review by SyntaxXSamurai — APPROVED** [review]
Great job on completing module-08.

**Comment by git160915** [comment]
Merging request.

**Comment by git160915** [comment]
Merging PR

**Pull request merged**
